-- local GeneralEntries, SubMenu = MenuEntries['general'], {}

-- local Buying = {
--     {
--         id = 'np-fuel:pdmmenushit',
--         title = "Set Commission",
--         icon = "#drivinginstructor-drivingtest",
--         event = "np-fuel:pdmmenushit"
--     },
--     {
--         id = 'np-pdm:testdrivepdm',
--         title = "Enable Test Drive",
--         icon = "#drivinginstructor",
--         event = "np-pdm:testdrivepdm"
--     },
--     {
--         id = 'np-pdm:enableBuypdm',
--         title = "Enable Purchase",
--         icon = "#animation-money",
--         event = "np-pdm:enableBuypdm"
--     },
-- }

-- Citizen.CreateThread(function()
--     for index, data in ipairs(Buying) do
--         SubMenu[index] = data.id
--         MenuItems[data.id] = {data = data}
--     end

--     GeneralEntries[#GeneralEntries+1] = {
--         data = {
--             id = "Buying",
--             icon = "#car",
--             title = "PDM" 
--         },
--         subMenus = SubMenu,
--         isEnabled = function(pEntity, pContext)
--             return (exports["np-business"]:IsEmployedAt("pdm") and exports['np-pdm']:isNearDealerShip() )
--         end,
--     }
-- end)